name: CI Check

on: [ push ]

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1

      - name: Set up JDK 11
        uses: actions/setup-java@v4.0.0
        with:
          java-version: '11'
          distribution: 'temurin'
          check-latest: true
          cache: gradle

      - name: Check
        run: ./gradlew check javadoc